application: helpinghallie
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.htm
  upload: index.htm

- url: /images
  static_dir: images

- url: /site.css
  static_files: site.css
  upload: site.css

- url: /(.*)
  static_files: \1
  upload: .*\.htm
